-- ════════════════════════════════════════════
-- GSTMIND DATABASE SCHEMA
-- Run this in Supabase SQL Editor
-- ════════════════════════════════════════════

-- ── USERS TABLE ──
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  phone text unique,
  name text not null,
  fname text,
  lname text,
  profession text,
  login_method text default 'email', -- 'email' or 'otp'
  plan text default 'free', -- 'free', 'pro', 'unlimited'
  query_count integer default 0,
  query_limit integer default 10,
  blocked boolean default false,
  joined_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ── QUERY HISTORY TABLE ──
create table if not exists public.query_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  query_text text not null,
  mode text default 'query', -- 'query' or 'draft'
  has_attachment boolean default false,
  created_at timestamptz default now()
);

-- ── QUERY LOG TABLE (for trending / analytics) ──
create table if not exists public.query_log (
  id uuid primary key default gen_random_uuid(),
  query_text text not null,
  mode text default 'query',
  count integer default 1,
  last_asked_at timestamptz default now()
);

-- ── SUBSCRIPTIONS TABLE ──
create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  plan text not null,
  razorpay_payment_id text,
  razorpay_order_id text,
  amount integer, -- in paise
  status text default 'active', -- 'active', 'cancelled', 'failed'
  started_at timestamptz default now(),
  expires_at timestamptz,
  created_at timestamptz default now()
);

-- ── OTP TABLE ──
create table if not exists public.otp_codes (
  id uuid primary key default gen_random_uuid(),
  phone text not null,
  code text not null,
  expires_at timestamptz not null,
  used boolean default false,
  created_at timestamptz default now()
);

-- ── KNOWLEDGE BASE TABLE ──
create table if not exists public.kb_documents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type text,
  content text not null,
  chunk_count integer default 0,
  is_builtin boolean default false,
  added_by text default 'admin',
  created_at timestamptz default now()
);

-- ── SYSTEM SETTINGS TABLE ──
create table if not exists public.settings (
  key text primary key,
  value text,
  updated_at timestamptz default now()
);

-- Insert default settings
insert into public.settings (key, value) values
  ('free_query_limit', '10'),
  ('pro_query_limit', '100'),
  ('disclaimer', 'This response is generated by GSTMind AI for research and reference purposes only. It does not constitute legal or professional advice.'),
  ('maintenance_mode', 'false')
on conflict (key) do nothing;

-- ── ROW LEVEL SECURITY ──
alter table public.users enable row level security;
alter table public.query_history enable row level security;
alter table public.query_log enable row level security;
alter table public.subscriptions enable row level security;
alter table public.otp_codes enable row level security;
alter table public.kb_documents enable row level security;
alter table public.settings enable row level security;

-- Users can only read/update their own data
create policy "Users can view own data" on public.users
  for select using (id::text = current_setting('request.jwt.claims', true)::json->>'sub');

create policy "Users can update own data" on public.users
  for update using (id::text = current_setting('request.jwt.claims', true)::json->>'sub');

-- Query history — users see only their own
create policy "Users see own history" on public.query_history
  for all using (user_id::text = current_setting('request.jwt.claims', true)::json->>'sub');

-- KB documents — everyone can read
create policy "Everyone can read KB" on public.kb_documents
  for select using (true);

-- Settings — everyone can read
create policy "Everyone can read settings" on public.settings
  for select using (true);

-- Service role bypasses all RLS (used by backend API)
